### ISSUE TITLE
Defaults fail to load

### ISSUE THREAD

**Issue by Bobhostern** [docopt/docopt.rs#182]
I have this usage string here, nearly verbatim:

```
Validates and packages a ***** project folder.

Usage:
    *******-packer <folder> [--output=FILE]
    *******-packer (--help | --version)
Options:
    --help          # Display this help message.
    --version       # Displays the program version.
    --output=<file> # Specifies a output name [default: game.grav].
```

Whenever I run it using this struct:

```rust
#[derive(RustcDecodable)]
struct Args {
    arg_folder: Option<String>,
    flag_output: String,
    flag_help: bool,
    flag_version: bool
}
```

and I use the command line: `*******-packer game`, it gives me `""` for `flag_output`, even though I specified a default. Is there anything I'm doing wrong?

**Comment by BurntSushi** [comment]
Could you please provide source code that I can compile and run? I can't reproduce your problem.

My `src/main.rs`:

```rust
extern crate docopt;
extern crate rustc_serialize;

use docopt::Docopt;

const USAGE: &'static str = "
Usage:
    prog <folder> [--output=FILE]
    prog (--help | --version)
Options:
    --help           # Display this help message.
    --version        # Displays the program version.
    --output=<file>  # Specifies a output name [default: game.grav].
";

#[derive(Debug, RustcDecodable)]
struct Args {
    arg_folder: Option<String>,
    flag_output: String,
    flag_help: bool,
    flag_version: bool,
}

fn main() {
    let args: Args = Docopt::new(USAGE).and_then(|d| d.decode())
                                       .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
}
```

My `Cargo.toml`:

```toml
[package]
name = "docopt-182"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
```

And running it:

```
$ cargo build
$ ./target/debug/docopt-182 game
Args { arg_folder: Some("game"), flag_output: "game.grav", flag_help: false, flag_version: false }
```

Which shows that `flag_output` gets the correct default value of `"game.grav"`.

**Comment by Bobhostern** [comment]
My main.rs:
```rust
extern crate tar;
extern crate bzip2;
extern crate base64;
extern crate docopt;
extern crate rustc_serialize;

const USAGE: &'static str = "
Validates and packages a Gravity project folder.

Usage:
    gravity-packer <folder> [--output=FILE]
    gravity-packer (--help | --version)
Options:
    --help          # Display this help message.
    --version       # Displays the program version.
    --output=FILE   # Specifies a output name [default: game.grav].
";

#[derive(Debug, RustcDecodable)]
struct Args {
    arg_folder: Option<String>,
    flag_output: String,
    flag_help: bool,
    flag_version: bool
}

use docopt::Docopt;

fn main() {
    let args: Args = Docopt::new(USAGE)
                            .and_then(|d| d.decode())
                            .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
    if args.arg_folder.is_some() {
        // Read folder w/ output
        println!("Output to {}?", args.flag_output);
    } else if args.flag_help {
        println!("{}", USAGE)
    } else if args.flag_version {
        println!("Version {}", option_env!("CARGO_PKG_VERSION").unwrap_or("unknown"))
    }
}
```

My Cargo.toml:
```toml
[package]
name = "gravity-packer"
version = "0.1.0"
authors = ["Bobhostern <bob.hostern@gmail.com>"]

[dependencies]
base64 = "0.1"
bzip2 = "0.3"
tar = "0.4"
docopt = "0.6"
rustc-serialize = "0.3"
walkdir = "0.1"
```

When I run the program with `cargo run -- game`, I get:
```
Compiling gravity-packer v0.1.0 (file:///C:/Users/Bobho_000/Documents/Rust/gravity/packer)
     Running `target\debug\gravity-packer.exe game`
Args { arg_folder: Some("game"), flag_output: "", flag_help: false, flag_version: false }
Output to ?
```
